# Generated by Django 4.1.3 on 2022-11-22 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=255)),
                ('infer_time', models.DateTimeField(blank=True, null=True)),
                ('task_status', models.CharField(default=0, max_length=1)),
                ('image_content', models.ImageField(upload_to='')),
            ],
        ),
    ]
