# Generated by Django 4.1.3 on 2022-11-22 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inferimages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagetask',
            name='task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
