# Generated by Django 4.1.3 on 2022-12-19 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inferimages', '0002_alter_imagetask_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagetask',
            name='task_status',
            field=models.BooleanField(default=False),
        ),
    ]
